<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit4be37ee904b9f96781b77b2b736a5a0e
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit4be37ee904b9f96781b77b2b736a5a0e::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit4be37ee904b9f96781b77b2b736a5a0e::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit4be37ee904b9f96781b77b2b736a5a0e::$classMap;

        }, null, ClassLoader::class);
    }
}
